const PaymentConst ={
    GET_PAYMENT_HISTORY_DASH : 'GET_PAYMENT_HISTORY_DASH',
    GET_PAYMENT_HISTORY_DASH_SUCCESS : 'GET_PAYMENT_HISTORY_DASH_SUCCESS',
    GET_PAYMENT_HISTORY_DASH_FAILED : 'GET_PAYMENT_HISTORY_DASH_FAILED',

    GET_BANK_REQUEST : 'GET_BANK_REQUEST',
    GET_BANK_REQUEST_SUCCESS : 'GET_BANK_REQUEST_SUCCESS',
    GET_BANK_REQUEST_FAILED : 'GET_BANK_REQUEST_FAILED',

    GET_ALL_BANK_REQUEST : 'GET_ALL_BANK_REQUEST',
    GET_ALL_BANK_REQUEST_SUCCESS : 'GET_ALL_BANK_REQUEST_SUCCESS',
    GET_ALL_BANK_REQUEST_FAILED : 'GET_ALL_BANK_REQUEST_FAILED',

    ADD_BANK : 'ADD_BANK',
    ADD_BANK_SUCCESS : 'ADD_BANK_SUCCESS',
    ADD_BANK_FAILED : 'ADD_BANK_FAILED',
    
    UPDATE_BANK : 'UPDATE_BANK',
    UPDATE_BANK_SUCCESS : 'UPDATE_BANK_SUCCESS',
    UPDATE_BANK_FAILED : 'UPDATE_BANK_FAILED',

    DELETE_BANK : 'DELETE_BANK',
    DELETE_BANK_SUCCESS : 'DELETE_BANK_SUCCESS',
    DELETE_BANK_FAILED : 'DELETE_BANK_FAILED',

    GET_PAYMENT_GATEWAY_REQUEST : 'GET_PAYMENT_GATEWAY_REQUEST',
    GET_PAYMENT_GATEWAY_REQUEST_SUCCESS : 'GET_PAYMENT_GATEWAY_REQUEST_SUCCESS',
    GET_PAYMENT_GATEWAY_REQUEST_FAILED : 'GET_PAYMENT_GATEWAY_REQUEST_FAILED',

    ADD_PAYMENT_GATEWAY : 'ADD_PAYMENT_GATEWAY',
    ADD_PAYMENT_GATEWAY_SUCCESS : 'ADD_PAYMENT_GATEWAY_SUCCESS',
    ADD_PAYMENT_GATEWAY_FAILED : 'ADD_PAYMENT_GATEWAY_FAILED',
    
    UPDATE_PAYMENT_GATEWAY : 'UPDATE_PAYMENT_GATEWAY',
    UPDATE_PAYMENT_GATEWAY_SUCCESS : 'UPDATE_PAYMENT_GATEWAY_SUCCESS',
    UPDATE_PAYMENT_GATEWAY_FAILED : 'UPDATE_PAYMENT_GATEWAY_FAILED',

    DELETE_PAYMENT_GATEWAY : 'DELETE_PAYMENT_GATEWAY',
    DELETE_PAYMENT_GATEWAY_SUCCESS : 'DELETE_PAYMENT_GATEWAY_SUCCESS',
    DELETE_PAYMENT_GATEWAY_FAILED : 'DELETE_PAYMENT_GATEWAY_FAILED',

    GET_ACCOUNT_ACTIVE : 'GET_ACCOUNT_ACTIVE',
    GET_ACCOUNT_ACTIVE_SUCCESS : 'GET_ACCOUNT_ACTIVE_SUCCESS',
    GET_ACCOUNT_ACTIVE_FAILED : 'GET_ACCOUNT_ACTIVE_FAILED',

    CREATE_ACCOUNT : 'CREATE_ACCOUNT',
    CREATE_ACCOUNT_SUCCESS : 'CREATE_ACCOUNT_SUCCESS',
    CREATE_ACCOUNT_FAILED : 'CREATE_ACCOUNT_FAILED',

    UPDATE_ACCOUNT : 'UPDATE_ACCOUNT',
    UPDATE_ACCOUNT_SUCCESS : 'UPDATE_ACCOUNT_SUCCESS',
    UPDATE_ACCOUNT_FAILED : 'UPDATE_ACCOUNT_FAILED',

    DELETE_ACCOUNT : 'DELETE_ACCOUNT',
    DELETE_ACCOUNT_SUCCESS : 'DELETE_ACCOUNT_SUCCESS',
    DELETE_ACCOUNT_FAILED : 'DELETE_ACCOUNT_FAILED',

    CHECK_SECURE_CODE : 'CHECK_SECURE_CODE',
    CHECK_SECURE_CODE_SUCCESS : 'CHECK_SECURE_CODE_SUCCESS',
    CHECK_SECURE_CODE_FAILED : 'CHECK_SECURE_CODE_FAILED',

    UPDATE_SECURE_CODE : 'UPDATE_SECURE_CODE',
    UPDATE_SECURE_CODE_SUCCESS : 'UPDATE_SECURE_CODE_SUCCESS',
    UPDATE_SECURE_CODE_FAILED : 'UPDATE_SECURE_CODE_FAILED',

    TOP_UP_WALLET : 'TOP_UP_WALLET',
    TOP_UP_WALLET_SUCCESS : 'TOP_UP_WALLET_SUCCESS',
    TOP_UP_WALLET_FAILED : 'TOP_UP_WALLET_FAILED',

    GET_HISTORY_PAYMENT : 'GET_HISTORY_PAYMENT',
    GET_HISTORY_PAYMENT_SUCCESS : 'GET_HISTORY_PAYMENT_SUCCESS',
    GET_HISTORY_PAYMENT_FAILED : 'GET_HISTORY_PAYMENT_FAILED',

    CREATE_TRANSACTION : 'CREATE_TRANSACTION',
    CREATE_TRANSACTION_SUCCESS : 'CREATE_TRANSACTION_SUCCESS',
    CREATE_TRANSACTION_FAILED : 'CREATE_TRANSACTION_FAILED',
}

export default PaymentConst