import PurchasingConst from "@/Redux/Constant/Purchasing/PurchasingConst";

export const AllStock = (): any => ({ type: PurchasingConst.GET_STOCKS })
export const AllStockSuccess = (payload: any): any => ({ type: PurchasingConst.GET_STOCKS_SUCCESS, payload })
export const AllStockFailed = (payload: any): any => ({ type: PurchasingConst.GET_STOCKS_FAILED, payload })
export const AllStockCart = (): any => ({ type: PurchasingConst.GET_STOCK_CART })
export const AllStockCartSuccess = (payload: any): any => ({ type: PurchasingConst.GET_STOCK_CART_SUCCESS, payload })
export const AllStockCartFailed = (payload: any): any => ({ type: PurchasingConst.GET_STOCK_CART_FAILED, payload })
export const AddStock = (payload: any): any => ({ type: PurchasingConst.ADD_STOCKS, payload })
export const AddStockSuccess = (payload: any): any => ({ type: PurchasingConst.ADD_STOCKS_SUCCESS, payload })
export const AddStockFailed = (payload: any): any => ({ type: PurchasingConst.ADD_STOCKS_FAILED, payload })
export const EditStock = (payload: any): any => ({ type: PurchasingConst.EDIT_STOCKS, payload })
export const EditStockSuccess = (payload: any): any => ({ type: PurchasingConst.EDIT_STOCKS_SUCCESS, payload })
export const EditStockFailed = (payload: any): any => ({ type: PurchasingConst.EDIT_STOCKS_FAILED, payload })
export const DelStock = (payload: any): any => ({ type: PurchasingConst.DEL_STOCKS, payload })
export const DelStockSuccess = (payload: any): any => ({ type: PurchasingConst.DEL_STOCKS_SUCCESS, payload })
export const DelStockFailed = (payload: any): any => ({ type: PurchasingConst.DEL_STOCKS_FAILED, payload })

export const AllStod = (): any => ({ type: PurchasingConst.GET_STOD })
export const AllStodSuccess = (payload: any): any => ({ type: PurchasingConst.GET_STOD_SUCCESS, payload })
export const AllStodFailed = (payload: any): any => ({ type: PurchasingConst.GET_STOD_FAILED, payload })
export const AddStod = (payload: any): any => ({ type: PurchasingConst.ADD_STOD, payload })
export const AddStodSuccess = (payload: any): any => ({ type: PurchasingConst.ADD_STOD_SUCCESS, payload })
export const AddStodFailed = (payload: any): any => ({ type: PurchasingConst.ADD_STOD_FAILED, payload })
export const EditStod = (payload: any): any => ({ type: PurchasingConst.EDIT_STOD, payload })
export const EditStodSuccess = (payload: any): any => ({ type: PurchasingConst.EDIT_STOD_SUCCESS, payload })
export const EditStodFailed = (payload: any): any => ({ type: PurchasingConst.EDIT_STOD_FAILED, payload })
export const DelStod = (payload: any): any => ({ type: PurchasingConst.DEL_STOD, payload })
export const DelStodSuccess = (payload: any): any => ({ type: PurchasingConst.DEL_STOD_SUCCESS, payload })
export const DelStodFailed = (payload: any): any => ({ type: PurchasingConst.DEL_STOD_FAILED, payload })

export const AllSpho = (): any => ({ type: PurchasingConst.GET_SPHO })
export const AllSphoSuccess = (payload: any): any => ({ type: PurchasingConst.GET_SPHO_SUCCESS, payload })
export const AllSphoFailed = (payload: any): any => ({ type: PurchasingConst.GET_SPHO_FAILED, payload })
export const AddSpho = (payload: any): any => ({ type: PurchasingConst.ADD_SPHO, payload })
export const AddSphoSuccess = (payload: any): any => ({ type: PurchasingConst.ADD_SPHO_SUCCESS, payload })
export const AddSphoFailed = (payload: any): any => ({ type: PurchasingConst.ADD_SPHO_FAILED, payload })
export const EditSpho = (payload: any): any => ({ type: PurchasingConst.EDIT_SPHO, payload })
export const EditSphoSuccess = (payload: any): any => ({ type: PurchasingConst.EDIT_SPHO_SUCCESS, payload })
export const EditSphoFailed = (payload: any): any => ({ type: PurchasingConst.EDIT_SPHO_FAILED, payload })
export const DelSpho = (payload: any): any => ({ type: PurchasingConst.DEL_SPHO, payload })
export const DelSphoSuccess = (payload: any): any => ({ type: PurchasingConst.DEL_SPHO_SUCCESS, payload })
export const DelSphoFailed = (payload: any): any => ({ type: PurchasingConst.DEL_SPHO_FAILED, payload })

export const AllVendor = (): any => ({ type: PurchasingConst.GET_VENDOR })
export const AllVendorSuccess = (payload: any): any => ({ type: PurchasingConst.GET_VENDOR_SUCCESS, payload })
export const AllVendorFailed = (payload: any): any => ({ type: PurchasingConst.GET_VENDOR_FAILED, payload })
export const AddVendor = (payload: any): any => ({ type: PurchasingConst.ADD_VENDOR, payload })
export const AddVendorSuccess = (payload: any): any => ({ type: PurchasingConst.ADD_VENDOR_SUCCESS, payload })
export const AddVendorFailed = (payload: any): any => ({ type: PurchasingConst.ADD_VENDOR_FAILED, payload })
export const EditVendor = (payload: any): any => ({ type: PurchasingConst.EDIT_VENDOR, payload })
export const EditVendorSuccess = (payload: any): any => ({ type: PurchasingConst.EDIT_VENDOR_SUCCESS, payload })
export const EditVendorFailed = (payload: any): any => ({ type: PurchasingConst.EDIT_VENDOR_FAILED, payload })
export const DelVendor = (payload: any): any => ({ type: PurchasingConst.DEL_VENDOR, payload })
export const DelVendorSuccess = (payload: any): any => ({ type: PurchasingConst.DEL_VENDOR_SUCCESS, payload })
export const DelVendorFailed = (payload: any): any => ({ type: PurchasingConst.DEL_VENDOR_FAILED, payload })

export const AllVepro = (): any => ({ type: PurchasingConst.GET_VEPRO })
export const AllVeproSuccess = (payload: any): any => ({ type: PurchasingConst.GET_VEPRO_SUCCESS, payload })
export const AllVeproFailed = (payload: any): any => ({ type: PurchasingConst.GET_VEPRO_FAILED, payload })
export const AddVepro = (payload: any): any => ({ type: PurchasingConst.ADD_VEPRO, payload })
export const AddVeproSuccess = (payload: any): any => ({ type: PurchasingConst.ADD_VEPRO_SUCCESS, payload })
export const AddVeproFailed = (payload: any): any => ({ type: PurchasingConst.ADD_VEPRO_FAILED, payload })
export const EditVepro = (payload: any): any => ({ type: PurchasingConst.EDIT_VEPRO, payload })
export const EditVeproSuccess = (payload: any): any => ({ type: PurchasingConst.EDIT_VEPRO_SUCCESS, payload })
export const EditVeproFailed = (payload: any): any => ({ type: PurchasingConst.EDIT_VEPRO_FAILED, payload })
export const DelVepro = (payload: any): any => ({ type: PurchasingConst.DEL_VEPRO, payload })
export const DelVeproSuccess = (payload: any): any => ({ type: PurchasingConst.DEL_VEPRO_SUCCESS, payload })
export const DelVeproFailed = (payload: any): any => ({ type: PurchasingConst.DEL_VEPRO_FAILED, payload })

export const AllPohe = () => ({ type: PurchasingConst.GET_POHE })
export const AllPoheSuccess = (payload: any) => ({ type: PurchasingConst.GET_POHE_SUCCESS, payload })
export const AllPoheFailed = (payload: any) => ({ type: PurchasingConst.GET_POHE_FAILED, payload })
export const AddPohe = (payload: any) => ({ type: PurchasingConst.ADD_POHE, payload })
export const AddPoheSuccess = (payload: any) => ({ type: PurchasingConst.ADD_POHE_SUCCESS, payload })
export const AddPoheFailed = (payload: any) => ({ type: PurchasingConst.ADD_POHE_FAILED, payload })
export const EditPohe = (payload: any) => ({ type: PurchasingConst.EDIT_POHE, payload })
export const EditPoheSuccess = (payload: any) => ({ type: PurchasingConst.EDIT_POHE_SUCCESS, payload })
export const EditPoheFailed = (payload: any) => ({ type: PurchasingConst.EDIT_POHE_FAILED, payload })
export const DelPohe = (payload: any) => ({ type: PurchasingConst.DEL_POHE, payload })
export const DelPoheSuccess = (payload: any) => ({ type: PurchasingConst.DEL_POHE_SUCCESS, payload })
export const DelPoheFailed = (payload: any) => ({ type: PurchasingConst.DEL_POHE_FAILED, payload })

export const AllPode = () => ({ type: PurchasingConst.GET_PODE })
export const AllPodeSuccess = (payload: any) => ({ type: PurchasingConst.GET_PODE_SUCCESS, payload })
export const AllPodeFailed = (payload: any) => ({ type: PurchasingConst.GET_PODE_FAILED, payload })
export const AddPode = (payload: any) => ({ type: PurchasingConst.ADD_PODE, payload })
export const AddPodeSuccess = (payload: any) => ({ type: PurchasingConst.ADD_PODE_SUCCESS, payload })
export const AddPodeFailed = (payload: any) => ({ type: PurchasingConst.ADD_PODE_FAILED, payload })
export const EditPode = (payload: any) => ({ type: PurchasingConst.EDIT_PODE, payload })
export const EditPodeSuccess = (payload: any) => ({ type: PurchasingConst.EDIT_PODE_SUCCESS, payload })
export const EditPodeFailed = (payload: any) => ({ type: PurchasingConst.EDIT_PODE_FAILED, payload })
export const DelPode = (payload: any) => ({ type: PurchasingConst.DEL_PODE, payload })
export const DelPodeSuccess = (payload: any) => ({ type: PurchasingConst.DEL_PODE_SUCCESS, payload })
export const DelPodeFailed = (payload: any) => ({ type: PurchasingConst.DEL_PODE_FAILED, payload })