
import Buttons from '@/components/Button'
import Hero from '@/components/restaurant.tsx/Hero'
import Layouts from '@/layouts/layout'
import { doRestoRequest } from '@/Redux/Action/Resto/restoAction'
import { configuration } from '@/Redux/Configs/url'
import { Card, Carousel, Col, Pagination, Row } from 'antd'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Router, { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { useDispatch, useSelector } from 'react-redux'

export default function index() {
  let dispatch = useDispatch();
  let restaurant = useSelector((state:any) => state.restoReducer.resto); 
  let router = useRouter()
   
  
  // PAGINATION
  
  const [currentpage, setCurrentPage] = useState(1);
  function handlePagination(page:any){
    setCurrentPage(page)
  }

  useEffect( () => {
    dispatch(doRestoRequest(currentpage))
  },[currentpage])

  function seeMenus(hotel:any){
    const hotel_name = hotel.hotel_name;
    const faci_name = hotel.faci_name;
    const faci_description = hotel.faci_description;
    const faci_id = hotel.faci_id;

    // router.push('/restaurant/menu/'+faci_id)
    router.push({
      pathname: '/restaurant/menu',
      query: {
        hotel_name,
        faci_name,
        // faci_description,
        faci_id
      },
    })
  } 
  return (
    <>
      <Head>
        <title>Hotel App | Restaurant</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/Hotel_Icon.png" />
      </Head>
      <main>
        <Layouts> 
          <br />
          <br />
        
          <div className='-z-10'>
          <Carousel autoplay>
            <img src="/assets/resto/1.jpg" alt="Restaurant" className='w-full object-cover object-bottom h-80 rounded-lg'/>
            <img src="/assets/resto/2.jpg" alt="Restaurant" className='w-full object-cover h-80' />
            <img src="/assets/resto/3.jpg" alt="Restaurant" className='w-full object-cover h-80' />
          </Carousel>
          </div>
          <div className='my-20 '>
            <h1 className='text-2xl text-center font-bold'>HOTEL REALTA SYSTEM RESTAURANT LIST</h1>

            {/* <hr className='my-10 border-t-2' /> */}

            <div className='container mx-auto '>

              {
                restaurant.data && restaurant.data.map( (hotel:any,index:any) =>
                  <>
                    <div className='border rounded-lg shadow-lg p-3 flex my-10 hover:bg-slate-100 bg-white'>
                      <img  src={`${configuration.BASE_URL}/facility-photos/`+hotel.fapho_thumbnail_filename} alt='Resto' width={250} height={250}></img>
                      <div className='ml-5'>
                        <h1 className='text-xl font-bold'>{hotel.hotel_name}</h1>
                        <h2 className='text-lg'>{hotel.faci_name}</h2>
                        <p>{hotel.faci_description}</p>
                        <div className='mt-4 right'>
                          <Buttons funcs={ () => seeMenus(hotel)}>
                            See menu
                          </Buttons>
                        </div>
                      </div>

                    </div>
                  </>
                )
              }

              
              <Pagination onChange={handlePagination} current={currentpage} total={restaurant.counts} className='text-center py-14' />

            </div>

          </div>
        </Layouts>
      </main>
    </>

  )
} 