// Menentukan Tipe Tindakan

const ActionTypes = {
  //-----------------------------------------------------------------------------------------------------------------------------------------
  // Table Regions
  //Get
  GET_REGIONS: 'GET_REGIONS',
  GET_REGIONS_SUCCEED: 'GET_REGIONS_SUCCEED',
  GET_REGIONS_FAILED: 'GET_REGIONS_FAILED',

  //Add
  ADD_REGIONS: 'ADD_REGIONS',
  ADD_REGIONS_SUCCEED: 'ADD_REGIONS_SUCCEED',
  ADD_REGIONS_FAILED: 'ADD_REGIONS_FAILED',

  //Update
  UPDATE_REGIONS: 'UPDATE_REGIONS',
  UPDATE_REGIONS_SUCCEED: 'UPDATE_REGIONS_SUCCEED',
  UPDATE_REGIONS_FAILED: 'UPDATE_REGIONS_FAILED',

  //Delete
  DEL_REGIONS: 'DEL_REGIONS',
  DEL_REGIONS_SUCCEED: 'DEL_REGIONS_SUCCEED',
  DEL_REGIONS_FAILED: 'DEL_REGIONS_FAILED',
  //-----------------------------------------------------------------------------------------------------------------------------------------
  // Table Country

  //Get
  GET_COUNTRY: 'GET_COUNTRY',
  GET_COUNTRY_SUCCEED: 'GET_COUNTRY_SUCCEED',
  GET_COUNTRY_FAILED: 'GET_COUNTRY_FAILED',

  //Add
  ADD_COUNTRY: 'ADD_COUNTRY',
  ADD_COUNTRY_SUCCEED: 'ADD_COUNTRY_SUCCEED',
  ADD_COUNTRY_FAILED: 'ADD_COUNTRY_FAILED',

  //Update
  UPDATE_COUNTRY: 'UPDATE_COUNTRY',
  UPDATE_COUNTRY_SUCCEED: 'UPDATE_COUNTRY_SUCCEED',
  UPDATE_COUNTRY_FAILED: 'UPDATE_COUNTRY_FAILED',

  //Del
  DEL_COUNTRY: 'DEL_COUNTRY',
  DEL_COUNTRY_SUCCEED: 'DEL_COUNTRY_SUCCEED',
  DEL_COUNTRY_FAILED: 'DEL_COUNTRY_FAILED',

  //-----------------------------------------------------------------------------------------------------------------------------------------
  // Table Provinces

  //Get
  GET_PROVINCES: 'GET_PROVINCES',
  GET_PROVINCES_SUCCEED: 'GET_PROVINCES_SUCCEED',
  GET_PROVINCES_FAILED: 'GET_PROVINCES_FAILED',

  //Add
  ADD_PROVINCES: 'ADD_PROVINCES',
  ADD_PROVINCES_SUCCEED: 'ADD_PROVINCES_SUCCEED',
  ADD_PROVINCES_FAILED: 'ADD_PROVINCES_FAILED',

  //Update
  UPDATE_PROVINCES: 'UPDATE_PROVINCES',
  UPDATE_PROVINCES_SUCCEED: 'UPDATE_PROVINCES_SUCCEED',
  UPDATE_PROVINCES_FAILED: 'UPDATE_PROVINCES_FAILED',

  //Del
  DEL_PROVINCES: 'DEL_PROVINCES',
  DEL_PROVINCES_SUCCEED: 'DEL_PROVINCES_SUCCEED',
  DEL_PROVINCES_FAILED: 'DEL_PROVINCES_FAILED',

  //-----------------------------------------------------------------------------------------------------------------------------------------
  // Table Address

  //   Get
  GET_ADDRESS: 'GET_ADDRESS',
  GET_ADDRESS_SUCCEED: 'GET_ADDRESS_SUCCEED',
  GET_ADDRESS_FAILED: 'GET_ADDRESS_FAILED',

  //Add
  ADD_ADDRESS: 'ADD_ADDRESS',
  ADD_ADDRESS_SUCCEED: 'ADD_ADDRESS_SUCCEED',
  ADD_ADDRESS_FAILED: 'ADD_ADDRESS_FAILED',

  //Update
  UPDATE_ADDRESS: 'UPDATE_ADDRESS',
  UPDATE_ADDRESS_SUCCEED: 'UPDATE_ADDRESS_SUCCEED',
  UPDATE_ADDRESS_FAILED: 'UPDATE_ADDRESS_FAILED',

  //Del
  DEL_ADDRESS: 'DEL_ADDRESS',
  DEL_ADDRESS_SUCCEED: 'DEL_ADDRESS_SUCCEED',
  DEL_ADDRESS_FAILED: 'DEL_ADDRESS_FAILED',

  //-------------------------------------------------------------------------------------------------------------------------------------------
  // Table Category_group

  //Get
  GET_CATEGORY_GROUP: 'GET_CATEGORY_GROUP',
  GET_CATEGORY_GROUP_SUCCEED: 'GET_CATEGORY_GROUP_SUCCEED',
  GET_CATEGORY_GROUP_FAILED: 'GET_CATEGORY_GROUP_FAILED',

  //Add
  ADD_CATEGORY_GROUP: 'ADD_CATEGORY_GROUP',
  ADD_CATEGORY_GROUP_SUCCEED: 'ADD_CATEGORY_GROUP_SUCCEED',
  ADD_CATEGORY_GROUP_FAILED: 'ADD_CATEGORY_GROUP_FAILED',

  //Update
  UPDATE_CATEGORY_GROUP: 'UPDATE_CATEGORY_GROUP',
  UPDATE_CATEGORY_GROUP_SUCCEED: 'UPDATE_CATEGORY_GROUP_SUCCEED',
  UPDATE_CATEGORY_GROUP_FAILED: 'UPDATE_CATEGORY_GROUP_FAILED',

  //Del
  DEL_CATEGORY_GROUP: 'DEL_CATEGORY_GROUP',
  DEL_CATEGORY_GROUP_SUCCEED: 'DEL_CATEGORY_GROUP_SUCCEED',
  DEL_CATEGORY_GROUP_FAILED: 'DEL_CATEGORY_GROUP_FAILED',

  //-------------------------------------------------------------------------------------------------------------------------------------------
  // Table Policy

  //Get
  GET_POLICY: 'GET_POLICY',
  GET_POLICY_SUCCEED: 'GET_POLICY_SUCCEED',
  GET_POLICY_FAILED: 'GET_POLICY_FAILED',

  //Add
  ADD_POLICY: 'ADD_POLICY',
  ADD_POLICY_SUCCEED: 'ADD_POLICY_SUCCEED',
  ADD_POLICY_FAILED: 'ADD_POLICY_FAILED',

  //Update
  UPDATE_POLICY: 'UPDATE_POLICY',
  UPDATE_POLICY_SUCCEED: 'UPDATE_POLICY_SUCCEED',
  UPDATE_POLICY_FAILED: 'UPDATE_POLICY_FAILED',

  //Del
  DEL_POLICY: 'DEL_POLICY',
  DEL_POLICY_SUCCEED: 'DEL_POLICY_SUCCEED',
  DEL_POLICY_FAILED: 'DEL_POLICY_FAILED',

  //-------------------------------------------------------------------------------------------------------------------------------------------
  // Table Policy_Category_group

  //Get
  GET_POLICY_CATEGORY_GROUP: 'GET_POLICY_CATEGORY_GROUP',
  GET_POLICY_CATEGORY_GROUP_SUCCEED: 'GET_POLICY_CATEGORY_GROUP_SUCCEED',
  GET_POLICY_CATEGORY_GROUP_FAILED: 'GET_POLICY_CATEGORY_GROUP_FAILED',

  //Add
  ADD_POLICY_CATEGORY_GROUP: 'ADD_POLICY_CATEGORY_GROUP',
  ADD_POLICY_CATEGORY_GROUP_SUCCEED: 'ADD_POLICY_CATEGORY_GROUP_SUCCEED',
  ADD_POLICY_CATEGORY_GROUP_FAILED: 'ADD_POLICY_CATEGORY_GROUP_FAILED',

  //Update
  UPDATE_POLICY_CATEGORY_GROUP: 'UPDATE_POLICY_CATEGORY_GROUP',
  UPDATE_POLICY_CATEGORY_GROUP_SUCCEED: 'UPDATE_POLICY_CATEGORY_GROUP_SUCCEED',
  UPDATE_POLICY_CATEGORY_GROUP_FAILED: 'UPDATE_POLICY_CATEGORY_GROUP_FAILED',

  //Del
  DEL_POLICY_CATEGORY_GROUP: 'DEL_POLICY_CATEGORY_GROUP',
  DEL_POLICY_CATEGORY_GROUP_SUCCEED: 'DEL_POLICY_CATEGORY_GROUP_SUCCEED',
  DEL_POLICY_CATEGORY_GROUP_FAILED: 'DEL_POLICY_CATEGORY_GROUP_FAILED',

  //-------------------------------------------------------------------------------------------------------------------------------------------
  // Table Price_items

  //Get
  GET_PRICE_ITEMS: 'GET_PRICE_ITEMS',
  GET_PRICE_ITEMS_SUCCEED: 'GET_PRICE_ITEMS_SUCCEED',
  GET_PRICE_ITEMS_FAILED: 'GET_PRICE_ITEMS_FAILED',

  //Add
  ADD_PRICE_ITEMS: 'ADD_PRICE_ITEMS',
  ADD_PRICE_ITEMS_SUCCEED: 'ADD_PRICE_ITEMS_SUCCEED',
  ADD_PRICE_ITEMS_FAILED: 'ADD_PRICE_ITEMS_FAILED',

  //Update
  UPDATE_PRICE_ITEMS: 'UPDATE_PRICE_ITEMS',
  UPDATE_PRICE_ITEMS_SUCCEED: 'UPDATE_PRICE_ITEMS_SUCCEED',
  UPDATE_PRICE_ITEMS_FAILED: 'UPDATE_PRICE_ITEMS_FAILED',

  //Del
  DEL_PRICE_ITEMS: 'DEL_PRICE_ITEMS',
  DEL_PRICE_ITEMS_SUCCEED: 'DEL_PRICE_ITEMS_SUCCEED',
  DEL_PRICE_ITEMS_FAILED: 'DEL_PRICE_ITEMS_FAILED',

  //-------------------------------------------------------------------------------------------------------------------------------------------
  // Table Service_task

  //Get
  GET_SERVICE_TASK: 'GET_SERVICE_TASK',
  GET_SERVICE_TASK_SUCCEED: 'GET_SERVICE_TASK_SUCCEED',
  GET_SERVICE_TASK_FAILED: 'GET_SERVICE_TASK_FAILED',

  //Add
  ADD_SERVICE_TASK: 'ADD_SERVICE_TASK',
  ADD_SERVICE_TASK_SUCCEED: 'ADD_SERVICE_TASK_SUCCEED',
  ADD_SERVICE_TASK_FAILED: 'ADD_SERVICE_TASK_FAILED',

  //Update
  UPDATE_SERVICE_TASK: 'UPDATE_SERVICE_TASK',
  UPDATE_SERVICE_TASK_SUCCEED: 'UPDATE_SERVICE_TASK_SUCCEED',
  UPDATE_SERVICE_TASK_FAILED: 'UPDATE_SERVICE_TASK_FAILED',

  //Del
  DEL_SERVICE_TASK: 'DEL_SERVICE_TASK',
  DEL_SERVICE_TASK_SUCCEED: 'DEL_SERVICE_TASK_SUCCEED',
  DEL_SERVICE_TASK_FAILED: 'DEL_SERVICE_TASK_FAILED',

  //-------------------------------------------------------------------------------------------------------------------------------------------
  // Table Members

  //Get
  GET_MEMBERS: 'GET_MEMBERS',
  GET_MEMBERS_SUCCEED: 'GET_MEMBERS',
  GET_MEMBERS_FAILED: 'GET_MEMBERS',

  //Add
  ADD_MEMBERS: 'ADD_MEMBERS',
  ADD_MEMBERS_SUCCEED: 'ADD_MEMBERS_SUCCEED',
  ADD_MEMBERS_FAILED: 'ADD_MEMBERS_FAILED',

  //Update
  UPDATE_MEMBERS: 'UPDATE_MEMBERS',
  UPDATE_MEMBERS_SUCCEED: 'UPDATE_MEMBERS_SUCCEED',
  UPDATE_MEMBERS_FAILED: 'UPDATE_MEMBERS_FAILED',

  //Del
  DEL_MEMBERS: 'DEL_MEMBERS',
  DEL_MEMBERS_SUCCEED: 'DEL_MEMBERS_SUCCEED',
  DEL_MEMBERS_FAILED: 'DEL_MEMBERS_FAILED',


   // Table Locations
  //Get
  GET_LOCATIONS: 'GET_LOCATIONS',
  GET_LOCATIONS_SUCCEED: 'GET_LOCATIONS_SUCCEED',
  GET_LOCATIONS_FAILED: 'GET_LOCATIONS_FAILED',

  //Add
  ADD_LOCATIONS: 'ADD_LOCATIONS',
  ADD_LOCATIONS_SUCCEED: 'ADD_LOCATIONS_SUCCEED',
  ADD_LOCATIONS_FAILED: 'ADD_LOCATIONS_FAILED',

  //Update
  UPDATE_LOCATIONS: 'UPDATE_LOCATIONS',
  UPDATE_LOCATIONS_SUCCEED: 'UPDATE_LOCATIONS_SUCCEED',
  UPDATE_LOCATIONS_FAILED: 'UPDATE_LOCATIONS_FAILED',

  //Delete
  DEL_LOCATIONS: 'DEL_LOCATIONS',
  DEL_LOCATIONS_SUCCEED: 'DEL_LOCATIONS_SUCCEED',
  DEL_LOCATIONS_FAILED: 'DEL_LOCATIONS_FAILED',
   
  
  // Table LocationsRC
  //Get
  GET_LOCATIONSRC: 'GET_LOCATIONSRC',
  GET_LOCATIONSRC_SUCCEED: 'GET_LOCATIONSRC_SUCCEED',
  GET_LOCATIONSRC_FAILED: 'GET_LOCATIONSRC_FAILED',

  //Add
  ADD_LOCATIONSRC: 'ADD_LOCATIONSRC',
  ADD_LOCATIONSRC_SUCCEED: 'ADD_LOCATIONSRC_SUCCEED',
  ADD_LOCATIONSRC_FAILED: 'ADD_LOCATIONSRC_FAILED',

  //Update
  UPDATE_LOCATIONSRC: 'UPDATE_LOCATIONSRC',
  UPDATE_LOCATIONSRC_SUCCEED: 'UPDATE_LOCATIONSRC_SUCCEED',
  UPDATE_LOCATIONSRC_FAILED: 'UPDATE_LOCATIONSRC_FAILED',

  //Delete
  DEL_LOCATIONSRC: 'DEL_LOCATIONSRC',
  DEL_LOCATIONSRC_SUCCEED: 'DEL_LOCATIONSRC_SUCCEED',
  DEL_LOCATIONSRC_FAILED: 'DEL_LOCATIONSRC_FAILED',
  //-----------------------------------------------------------------------------------------------------------------------------------------
  
  // Table LocationsRC
  //Get
  GET_LOCATIONSRCP: 'GET_LOCATIONSRCP',
  GET_LOCATIONSRCP_SUCCEED: 'GET_LOCATIONSRCP_SUCCEED',
  GET_LOCATIONSRCP_FAILED: 'GET_LOCATIONSRCP_FAILED',

  //Add
  ADD_LOCATIONSRCP: 'ADD_LOCATIONSRCP',
  ADD_LOCATIONSRCP_SUCCEED: 'ADD_LOCATIONSRCP_SUCCEED',
  ADD_LOCATIONSRCP_FAILED: 'ADD_LOCATIONSRCP_FAILED',

  //Update
  UPDATE_LOCATIONSRCP: 'UPDATE_LOCATIONSRCP',
  UPDATE_LOCATIONSRCP_SUCCEED: 'UPDATE_LOCATIONSRCP_SUCCEED',
  UPDATE_LOCATIONSRCP_FAILED: 'UPDATE_LOCATIONSRCP_FAILED',

  //Delete
  DEL_LOCATIONSRCP: 'DEL_LOCATIONSRCP',
  DEL_LOCATIONSRCP_SUCCEED: 'DEL_LOCATIONSRCP_SUCCEED',
  DEL_LOCATIONSRCP_FAILED: 'DEL_LOCATIONSRCP_FAILED',
  //-----------------------------------------------------------------------------------------------------------------------------------------
  
};

export default ActionTypes;
