const UserConst = {
    // Auth
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILED: 'LOGIN_USER_FAILED',

    LOGOUT_USER: 'LOGOUT_USER',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILED: 'LOGOUT_USER_FAILED',


    // Get Data User
    GET_DATA_USER : 'GET_DATA_USER',
    DATA_USER_SUCCESS : 'DATA_USER_GET_SUCCESS',
    DATA_USER_FAILED : 'DATA_USER_GET_FAILED',

    //Create Data User
    ADD_DATA_USER :'ADD_DATA_USER',
    ADD_DATA_USER_SUCCESS : 'ADD_DATA_USER_SUCCESS',
    ADD_DATA_USER_FAILED : 'ADD_DATA_USER_FAILED',

    // Edit Data
    EDIT_DATA_PROFILE : 'EDIT_DATA_PROFILE',
    EDIT_DATA_PROFILE_SUCCESS : 'EDIT_DATA_PROFILE_SUCCESS',
    EDIT_DATA_PROFILE_FAILED : 'EDIT_DATA_PROFILE_FAILED',

    //Update_Password
    UPDATE_PASSWORD : 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_SUCCESS : 'UPDATE_PASSWORD',
    UPDATE_PASSWORD_FAILED : 'UPDATE_PASSWORD',

    



}

export default UserConst;