const PurchasingConst = {
    // STOCKS
    GET_STOCKS: "GET_STOCKS",
    GET_STOCKS_SUCCESS: "GET_STOCKS_SUCCESS",
    GET_STOCKS_FAILED: "GET_STOCKS_FAILED",

    GET_STOCK_CART: "GET_STOCK_CART",
    GET_STOCK_CART_SUCCESS: "GET_STOCK_CART_SUCCESS",
    GET_STOCK_CART_FAILED: "GET_STOCK_CART_FAILED",

    ADD_STOCKS: "ADD_STOCKS",
    ADD_STOCKS_SUCCESS: "ADD_STOCKS_SUCCESS",
    ADD_STOCKS_FAILED: "ADD_STOCKS_FAILED",

    EDIT_STOCKS: "EDIT_STOCKS",
    EDIT_STOCKS_SUCCESS: "EDIT_STOCKS_SUCCESS",
    EDIT_STOCKS_FAILED: "EDIT_STOCKS_FAILED",

    DEL_STOCKS: "DEL_STOCKS",
    DEL_STOCKS_SUCCESS: "DEL_STOCKS_SUCCESS",
    DEL_STOCKS_FAILED: "DEL_STOCKS_FAILED",

    // STOCKS DETAILS
    GET_STOD: "GET_STOD",
    GET_STOD_SUCCESS: "GET_STOD_SUCCESS",
    GET_STOD_FAILED: "GET_STOD_FAILED",

    ADD_STOD: "ADD_STOD",
    ADD_STOD_SUCCESS: "ADD_STOD_SUCCESS",
    ADD_STOD_FAILED: "ADD_STOD_FAILED",

    EDIT_STOD: "EDIT_STOD",
    EDIT_STOD_SUCCESS: "EDIT_STOD_SUCCESS",
    EDIT_STOD_FAILED: "EDIT_STOD_FAILED",

    DEL_STOD: "DEL_STOD",
    DEL_STOD_SUCCESS: "DEL_STOD_SUCCESS",
    DEL_STOD_FAILED: "DEL_STOD_FAILED",

    // STOCKS PHOTO
    GET_SPHO: "GET_SPHO",
    GET_SPHO_SUCCESS: "GET_SPHO_SUCCESS",
    GET_SPHO_FAILED: "GET_SPHO_FAILED",

    ADD_SPHO: "ADD_SPHO",
    ADD_SPHO_SUCCESS: "ADD_SPHO_SUCCESS",
    ADD_SPHO_FAILED: "ADD_SPHO_FAILED",

    EDIT_SPHO: "EDIT_SPHO",
    EDIT_SPHO_SUCCESS: "EDIT_SPHO_SUCCESS",
    EDIT_SPHO_FAILED: "EDIT_SPHO_FAILED",

    DEL_SPHO: "DEL_SPHO",
    DEL_SPHO_SUCCESS: "DEL_SPHO_SUCCESS",
    DEL_SPHO_FAILED: "DEL_SPHO_FAILED",

    // VENDOR
    GET_VENDOR: "GET_VENDOR",
    GET_VENDOR_SUCCESS: "GET_VENDOR_SUCCESS",
    GET_VENDOR_FAILED: "GET_VENDOR_FAILED",

    ADD_VENDOR: "ADD_VENDOR",
    ADD_VENDOR_SUCCESS: "ADD_VENDOR_SUCCESS",
    ADD_VENDOR_FAILED: "ADD_VENDOR_FAILED",

    EDIT_VENDOR: "EDIT_VENDOR",
    EDIT_VENDOR_SUCCESS: "EDIT_VENDOR_SUCCESS",
    EDIT_VENDOR_FAILED: "EDIT_VENDOR_FAILED",

    DEL_VENDOR: "DEL_VENDOR",
    DEL_VENDOR_SUCCESS: "DEL_VENDOR_SUCCESS",
    DEL_VENDOR_FAILED: "DEL_VENDOR_FAILED",

    // VENDOR PRODUCT
    GET_VEPRO: "GET_VEPRO",
    GET_VEPRO_SUCCESS: "GET_VEPRO_SUCCESS",
    GET_VEPRO_FAILED: "GET_VEPRO_FAILED",

    ADD_VEPRO: "ADD_VEPRO",
    ADD_VEPRO_SUCCESS: "ADD_VEPRO_SUCCESS",
    ADD_VEPRO_FAILED: "ADD_VEPRO_FAILED",

    EDIT_VEPRO: "EDIT_VEPRO",
    EDIT_VEPRO_SUCCESS: "EDIT_VEPRO_SUCCESS",
    EDIT_VEPRO_FAILED: "EDIT_VEPRO_FAILED",

    DEL_VEPRO: "DEL_VEPRO",
    DEL_VEPRO_SUCCESS: "DEL_VEPRO_SUCCESS",
    DEL_VEPRO_FAILED: "DEL_VEPRO_FAILED",

    // PURCHASE ORDER HEADER
    GET_POHE: "GET_POHE",
    GET_POHE_SUCCESS: "GET_POHE_SUCCESS",
    GET_POHE_FAILED: "GET_POHE_FAILED",

    ADD_POHE: "ADD_POHE",
    ADD_POHE_SUCCESS: "ADD_POHE_SUCCESS",
    ADD_POHE_FAILED: "ADD_POHE_FAILED",

    EDIT_POHE: "EDIT_POHE",
    EDIT_POHE_SUCCESS: "EDIT_POHE_SUCCESS",
    EDIT_POHE_FAILED: "EDIT_POHE_FAILED",

    DEL_POHE: "DEL_POHE",
    DEL_POHE_SUCCESS: "DEL_POHE_SUCCESS",
    DEL_POHE_FAILED: "DEL_POHE_FAILED",

    // PURCHASE ORDER DETAIL
    GET_PODE: "GET_PODE",
    GET_PODE_SUCCESS: "GET_PODE_SUCCESS",
    GET_PODE_FAILED: "GET_PODE_FAILED",

    ADD_PODE: "ADD_PODE",
    ADD_PODE_SUCCESS: "ADD_PODE_SUCCESS",
    ADD_PODE_FAILED: "ADD_PODE_FAILED",

    EDIT_PODE: "EDIT_PODE",
    EDIT_PODE_SUCCESS: "EDIT_PODE_SUCCESS",
    EDIT_PODE_FAILED: "EDIT_PODE_FAILED",

    DEL_PODE: "DEL_PODE",
    DEL_PODE_SUCCESS: "DEL_PODE_SUCCESS",
    DEL_PODE_FAILED: "DEL_PODE_FAILED",
}

export default PurchasingConst