const BookingConstant = {
    GET_SPOF : 'GET_SPOF',
    GET_SPOF_SUCCESS : 'GET_SPOF_SUCCEESS',
    GET_SPOF_FAILED : 'GET_SPOF_FAILED',

    GET_BOOR : 'GET_BOOR',
    GET_BOOR_SUCCESS : 'GET_BOOR_SUCCESS',
    GET_BOOR_FAILED : 'GET_BOOR_FAILED',

    GET_BORDE : 'GET_BORDE',
    GET_BORDE_SUCCESS : 'GET_BORDE_SUCCESS',
    GET_BORDE_FAILED : 'GET_BORDE_FAILED',

    GET_SP_HOTEL : 'GET_SP_HOTEL',
    GET_SP_HOTEL_SUCCESS : 'GET_SP_HOTEL_SUCCESS',
    GET_SP_HOTEL_FAILED : 'GET_SP_HOTEL_FAILED',

    GET_SP_FACILITIES : 'GET_SP_FACILITIES',
    GET_SP_FACILITIES_SUCCESS : 'GET_SP_FACILITIES_SUCCESS',
    GET_SP_FACILITIES_FAILED : 'GET_SP_FACILITIES_FAILED',

    GET_SP_REVIEW : 'GET_SP_REVIEW',
    GET_SP_REVIEW_SUCCESS : 'GET_SP_REVIEW_SUCCESS',
    GET_SP_REVIEW_FAILED : 'GET_SP_REVIEW_FAILED',

    INSERT_BOOKING_ORDER : 'INSERT_BOOKING_ORDER',
    INSERT_BOOKING_ORDER_SUCCESS : 'INSERT_BOOKING_ORDER_SUCCESS',
    INSERT_BOOKING_ORDER_FAILED : 'INSERT_BOOKING_ORDER_SUCCESS',

    INSERT_BOOKING_EXTRA : 'INSERT_BOOKING_EXTRA',
    INSERT_BOOKING_EXTRA_SUCCESS : 'INSERT_BOOKING_EXTRA_SUCCESS',
    INSERT_BOOKING_EXTRA_FAILED : 'INSERT_BOOKING_EXTRA_fAILED',
    
    GET_SP_INVOICE : 'GET_SP_INVOICE',
    GET_SP_INVOICE_SUCCESS : 'GET_SP_INVOICE_SUCCESS',
    GET_SP_INVOICE_FAILED : 'GET_SP_INVOICE_FAILED',



}

export default BookingConstant