const menuConstant = {
    // for resto menu
    GET_MENUS: 'GET_MENUS',
    GET_MENUS_SUCCEED: 'GET_MENUS_SUCCEED',
    GET_MENUS_FAILED: 'GET_MENUS_FAILED',
    
    UPDATE_MENU: 'UPDATE_MENU',
    UPDATE_MENU_SUCCEED: 'UPDATE_MENU_SUCCEED',
    UPDATE_MENU_FAILED: 'UPDATE_MENU_FAILED',

    ADD_MENU: 'ADD_MENU',
    ADD_MENU_SUCCEED: 'ADD_MENU_SUCCEED',
    ADD_MENU_FAILED: 'ADD_MENU_FAILED',

    DELETE_MENU: 'DELETE_MENU',
    DELETE_MENU_SUCCEED: 'DELETE_MENU_SUCCEED',
    DELETE_MENU_FAILED: 'DELETE_MENU_FAILED'
}

export default menuConstant;