const numberOrderConst = {
    GET_NUMBER_ORDER : 'GET_NUMBER_ORDER',
    GET_NUMBER_ORDER_SUCCEED : 'GET_NUMBER_ORDER_SUCCEED',
    GET_NUMBER_ORDER_FAILED : 'GET_NUMBER_ORDER_FAILED'
}

export default numberOrderConst;