const orderConstant = {
    ADD_ORDERS : 'ADD_ORDERS',
    ADD_ORDERS_SUCCEED : 'ADD_ORDERS_SUCCEED',
    ADD_ORDERS_FAILED: 'ADD_ORDERS_FAILED',

    GET_ORDERS : 'GET_ORDERS',
    GET_ORDERS_SUCCEED : 'GET_ORDERS_SUCCEED',
    GET_ORDERS_FAILED : 'GET_ORDERS_FAILED'
}

export default orderConstant;