const photoConstant = {
  GET_PHOTO: 'GET_PHOTO',
  GET_PHOTO_SUCCEED: 'GET_PHOTO_SUCCEED',
  GET_PHOTO_FAILED: 'GET_PHOTO_FAILED',

  ADD_PHOTO: 'ADD_PHOTO',
  ADD_PHOTO_SUCCEED: 'ADD_PHOTO_SUCCEED',
  ADD_PHOTO_FAILED: 'ADD_PHOTO_FAILED',

  DELETE_PHOTO: 'DELETE_PHOTO',
  DELETE_PHOTO_SUCCEED: 'DELETE_PHOTO_SUCCEED',
  DELETE_PHOTO_FAILED: 'DELETE_PHOTO_FAILED',

  UPDATE_PRIMARY: 'UPDATE_PRIMARY',
  UPDATE_PRIMARY_SUCCEED: 'UPDATE_PRIMARY_SUCCEED',
  UPDATE_PRIMARY_FAILED: 'UPDATE_PRMARY_FAILED'
}

export default photoConstant;