const userOrderConstant = {
    GET_ORDER_COMPLETE : 'GET_ORDER_COMPLETE',
    GET_ORDER_COMPLETE_SUCCEED : 'GET_ORDER_COMPLETE_SUCCEED',
    GET_ORDER_COMPLETE_FAILED : 'GET_ORDER_COMPLETE_FAILED' 
}

export default userOrderConstant;