export const deptType = {
    GET_DATA: 'GET_DEPT',
    GET_DATA_SUCCESS: 'GET_DEPT_SUCCESS',
    GET_DATA_FAILED: 'GET_DEPT_FAILED',
    ADD_DATA: 'ADD_DEPT',
    ADD_DATA_SUCCESS: 'ADD_DEPT_SUCCESS',
    ADD_DATA_FAILED: 'ADD_DEPT_FAILED',
    UPDATE_DATA: 'UPDATE_DEPT',
    UPDATE_DATA_SUCCESS: 'UPDATE_DEPT_SUCCESS',
    UPDATE_DATA_FAILED: 'UPDATE_DEPT_FAILED',
    DELETE_DATA: 'DELETE_DEPT',
    DELETE_DATA_SUCCESS: 'DELETE_DEPT_SUCCESS',
    DELETE_DATA_FAILED: 'DELETE_DEPT_FAILED',
    GET_SELECT: 'GET_DEPT_SELECT',
    GET_SELECT_SUCCESS: 'GET_DEPT_SELECT_SUCCESS',
    GET_SELECT_FAILED: 'GET_DEPT_SELECT_FAILED'
}