import Footer from '@/components/Footer'
import Headers from '@/components/Headers'
import { Layout } from 'antd'
import { Props } from 'next/script'
import {useState} from 'react'
import {
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    UploadOutlined,
    UserOutlined,
    VideoCameraOutlined,
  } from '@ant-design/icons';
import Head from 'next/head'
import  {useRouter}  from 'next/router'

const Layouts = ({children}:Props) => {
    const router = useRouter()
    const { location, date } = router.query
    const nav = [
        {
            name: 'Home',
            href: '/'
        },
        {
            name: 'Hotels',
            href: '/booking'
        },
        {
            name: 'Restaurants',
            href: '/restaurant'
        }
    ]
    return(
        <>
            <Head>
                <title>Hotel App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/assets/icons.png"/>
            </Head>
            <Layout className='bg-[#F2F1FA]'>
                <Headers nav={nav} queries={[location, {date: date}]} logo="/assets/icons.png"/>
                <main className=' border-0 align-items-center container m-auto min-h-screen'>
                    {children}
                </main>
                <Footer service={nav}/>
            </Layout>
        </>
    )
}
export default Layouts